type: map
mapping:
  "information":
    type: seq
    sequence:
      - type: str
  "links":
    required: false
    type: map
    mapping:
      "documentation":
        type: str
        required: true
      "credit":
        type: str
        required: false
  "defaults":
    type: any
  "parameters":
    type: any
  "locationId":
    type: str
  "safeMode":
    type: bool
  "polishers":
    type: seq
    sequence:
      - type: map
        matching-rule: 'any'
        mapping:
          regex;(.+):
            type: map
            mapping:
              "key":
                type: str
              "reap":
                type: str
  "blueprints":
    type: seq
    sequence:
      - type: map
        matching-rule: 'any'
        mapping:
          regex;(.+):
            type: map
            mapping:
              "ethernet":
                type: any
              "domain":
                type: map
                mapping:
                  "name":
                    type: str
                    required: true
                  "description":
                    type: str
                  "service":
                    type: str
                    enum: ['essentials','advanced']
                  "ipv4":
                    type: text
              "nodes":
                type: seq
                sequence:
                  - type: map
                    matching-rule: 'any'
                    mapping:
                      regex;(.+):
                        type: map
                        mapping:
                          "default":
                            type: str
                          "appliance":
                            type: str
                          "cpu":
                            desc: "Number of CPU"
                            type: int
                          "memory":
                            desc: "Amount of RAM in GB"
                            type: int
                          "disks":
                            type: seq
                            sequence:
                              - type: str
                          "cloud-config":
                            type: any
                          "description":
                            type: str
                          "glue":
                            type: seq
                            sequence:
                              - type: str
                          "running":
                            type: str
                            enum: ['always']
                          "monitoring":
                            type: str
                            enum: ['essentials','advanced']
                          "information":
                            type: seq
                            sequence:
                              - type: str
